### ISSUE TITLE
0.3.6 版本，日历图标看不到

### ISSUE THREAD

**Issue by kangning1206** [uxcore/uxcore-calendar#18]
项目中使用到版本0.3.6，文本框右侧日历图标 
```
<i class="kuma-icon kuma-icon-calender" unselectable="true"></i>
```
看不到了，dom上是不存在的，demo站点
http://uxco.re/components/calendar/ 上是0.3.9，也没有显示出来。

**Comment by eternalsky** [comment]
https://github.com/uxcore/uxcore-calendar/commit/fb8eb282e1bdaf2f69861ab177b39d66f104368a
