### ISSUE TITLE
timePicker的showSecond配置无效

### ISSUE THREAD

**Issue by McLemore** [uxcore/uxcore-calendar#22]
时刻选择，精确到秒不是必须的，有些场景下只需要选择时、分，如：新建一个会议。默认的timePicker组件rc-time-picker是支持配置showSecond的，但是在uxocre-calendar的RcCalendar文件中将showSecond写死为true了，能否提供支持showSecond配置。

**Comment by eternalsky** [comment]
这个样式上也得跟着做出一些修改，不能直接传给 timePicker。但是可以。考虑让 calendar 支持一下这个配置。

**Comment by eternalsky** [comment]
fix in ver. 0.6.3
